/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteRouteImport } from './routes/access/route'
import { Route as ApplicationsRouteRouteImport } from './routes/applications/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as AccessIndexRouteImport } from './routes/access/index'
import { Route as ApiIdentityRouteImport } from './routes/api/identity'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiStudentVerificationRouteImport } from './routes/api/student-verification'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsClientIdRouteImport } from './routes/applications/$clientId'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as ApplicationsServiceNewRouteImport } from './routes/applications/service-new'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as AccessPermissionsIndexRouteImport } from './routes/access/permissions/index'
import { Route as AccessPermissionsPermissionIdRouteImport } from './routes/access/permissions/$permissionId'
import { Route as AccessPermissionsNewRouteImport } from './routes/access/permissions/new'
import { Route as AccessRolesIndexRouteImport } from './routes/access/roles/index'
import { Route as AccessRolesRoleIdRouteImport } from './routes/access/roles/$roleId'
import { Route as AccessRolesNewRouteImport } from './routes/access/roles/new'
import { Route as ApiAccountsUnlinkRouteImport } from './routes/api/accounts/unlink'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev/login'
import { Route as ApiIdpAccessRouteImport } from './routes/api/idp/access'
import { Route as ApiInternalAccessSnapshotRouteImport } from './routes/api/internal/access-snapshot'
import { Route as ApiOidcClientUpdateRouteImport } from './routes/api/oidc/client-update'
import { Route as ApiOidcClientsRouteImport } from './routes/api/oidc/clients'
import { Route as ApiOidcResourceLinkRouteImport } from './routes/api/oidc/resource-link'
import { Route as ApiOidcServiceClientRouteImport } from './routes/api/oidc/service-client'
import { Route as ApiRbacCatalogRouteImport } from './routes/api/rbac/catalog'
import { Route as ApiRbacPermissionSaveRouteImport } from './routes/api/rbac/permission-save'
import { Route as ApiRbacRoleMembersRouteImport } from './routes/api/rbac/role-members'
import { Route as ApiRbacRoleSaveRouteImport } from './routes/api/rbac/role-save'
import { Route as ApiRbacUsersRouteImport } from './routes/api/rbac/users'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRouteRoute = AccessRouteRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRouteRoute = ApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessIndexRoute = AccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const ApiIdentityRoute = ApiIdentityRouteImport.update({
  id: '/api/identity',
  path: '/api/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentVerificationRoute = ApiStudentVerificationRouteImport.update({
  id: '/api/student-verification',
  path: '/api/student-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const ApplicationsClientIdRoute = ApplicationsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const ApplicationsServiceNewRoute = ApplicationsServiceNewRouteImport.update({
  id: '/service-new',
  path: '/service-new',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const AccessPermissionsIndexRoute = AccessPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessPermissionsPermissionIdRoute =
  AccessPermissionsPermissionIdRouteImport.update({
    id: '/permissions/$permissionId',
    path: '/permissions/$permissionId',
    getParentRoute: () => AccessRouteRoute,
  } as any)
const AccessPermissionsNewRoute = AccessPermissionsNewRouteImport.update({
  id: '/permissions/new',
  path: '/permissions/new',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesIndexRoute = AccessRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesRoleIdRoute = AccessRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesNewRoute = AccessRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AccessRouteRoute,
} as any)
const ApiAccountsUnlinkRoute = ApiAccountsUnlinkRouteImport.update({
  id: '/api/accounts/unlink',
  path: '/api/accounts/unlink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev/login',
  path: '/api/dev/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdpAccessRoute = ApiIdpAccessRouteImport.update({
  id: '/api/idp/access',
  path: '/api/idp/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAccessSnapshotRoute =
  ApiInternalAccessSnapshotRouteImport.update({
    id: '/api/internal/access-snapshot',
    path: '/api/internal/access-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOidcClientUpdateRoute = ApiOidcClientUpdateRouteImport.update({
  id: '/api/oidc/client-update',
  path: '/api/oidc/client-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcClientsRoute = ApiOidcClientsRouteImport.update({
  id: '/api/oidc/clients',
  path: '/api/oidc/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcResourceLinkRoute = ApiOidcResourceLinkRouteImport.update({
  id: '/api/oidc/resource-link',
  path: '/api/oidc/resource-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcServiceClientRoute = ApiOidcServiceClientRouteImport.update({
  id: '/api/oidc/service-client',
  path: '/api/oidc/service-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacCatalogRoute = ApiRbacCatalogRouteImport.update({
  id: '/api/rbac/catalog',
  path: '/api/rbac/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacPermissionSaveRoute = ApiRbacPermissionSaveRouteImport.update({
  id: '/api/rbac/permission-save',
  path: '/api/rbac/permission-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacRoleMembersRoute = ApiRbacRoleMembersRouteImport.update({
  id: '/api/rbac/role-members',
  path: '/api/rbac/role-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacRoleSaveRoute = ApiRbacRoleSaveRouteImport.update({
  id: '/api/rbac/role-save',
  path: '/api/rbac/role-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacUsersRoute = ApiRbacUsersRouteImport.update({
  id: '/api/rbac/users',
  path: '/api/rbac/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/api/users/$userId',
  path: '/api/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRouteRouteWithChildren
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/service-new': typeof ApplicationsServiceNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/access/': typeof AccessIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/internal/access-snapshot': typeof ApiInternalAccessSnapshotRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/oidc/resource-link': typeof ApiOidcResourceLinkRoute
  '/api/oidc/service-client': typeof ApiOidcServiceClientRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/access/permissions/': typeof AccessPermissionsIndexRoute
  '/access/roles/': typeof AccessRolesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/service-new': typeof ApplicationsServiceNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/access': typeof AccessIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/users': typeof UsersIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/internal/access-snapshot': typeof ApiInternalAccessSnapshotRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/oidc/resource-link': typeof ApiOidcResourceLinkRoute
  '/api/oidc/service-client': typeof ApiOidcServiceClientRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/access/permissions': typeof AccessPermissionsIndexRoute
  '/access/roles': typeof AccessRolesIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRouteRouteWithChildren
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/service-new': typeof ApplicationsServiceNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/access/': typeof AccessIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/internal/access-snapshot': typeof ApiInternalAccessSnapshotRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/oidc/resource-link': typeof ApiOidcResourceLinkRoute
  '/api/oidc/service-client': typeof ApiOidcServiceClientRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/access/permissions/': typeof AccessPermissionsIndexRoute
  '/access/roles/': typeof AccessRolesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/applications'
    | '/users'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/applications/service-new'
    | '/users/$userId'
    | '/access/'
    | '/applications/'
    | '/users/'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/idp/access'
    | '/api/internal/access-snapshot'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/oidc/resource-link'
    | '/api/oidc/service-client'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/api/users/$userId'
    | '/access/permissions/'
    | '/access/roles/'
    | '/api/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/applications/service-new'
    | '/users/$userId'
    | '/access'
    | '/applications'
    | '/users'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/idp/access'
    | '/api/internal/access-snapshot'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/oidc/resource-link'
    | '/api/oidc/service-client'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/api/users/$userId'
    | '/access/permissions'
    | '/access/roles'
    | '/api/users'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/applications'
    | '/users'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/applications/service-new'
    | '/users/$userId'
    | '/access/'
    | '/applications/'
    | '/users/'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/idp/access'
    | '/api/internal/access-snapshot'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/oidc/resource-link'
    | '/api/oidc/service-client'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/api/users/$userId'
    | '/access/permissions/'
    | '/access/roles/'
    | '/api/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRouteRoute: typeof AccessRouteRouteWithChildren
  ApplicationsRouteRoute: typeof ApplicationsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  ApiIdentityRoute: typeof ApiIdentityRoute
  ApiProvidersRoute: typeof ApiProvidersRoute
  ApiStudentVerificationRoute: typeof ApiStudentVerificationRoute
  ApiAccountsUnlinkRoute: typeof ApiAccountsUnlinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiIdpAccessRoute: typeof ApiIdpAccessRoute
  ApiInternalAccessSnapshotRoute: typeof ApiInternalAccessSnapshotRoute
  ApiOidcClientUpdateRoute: typeof ApiOidcClientUpdateRoute
  ApiOidcClientsRoute: typeof ApiOidcClientsRoute
  ApiOidcResourceLinkRoute: typeof ApiOidcResourceLinkRoute
  ApiOidcServiceClientRoute: typeof ApiOidcServiceClientRoute
  ApiRbacCatalogRoute: typeof ApiRbacCatalogRoute
  ApiRbacPermissionSaveRoute: typeof ApiRbacPermissionSaveRoute
  ApiRbacRoleMembersRoute: typeof ApiRbacRoleMembersRoute
  ApiRbacRoleSaveRoute: typeof ApiRbacRoleSaveRoute
  ApiRbacUsersRoute: typeof ApiRbacUsersRoute
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/': {
      id: '/access/'
      path: '/'
      fullPath: '/access/'
      preLoaderRoute: typeof AccessIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/api/identity': {
      id: '/api/identity'
      path: '/api/identity'
      fullPath: '/api/identity'
      preLoaderRoute: typeof ApiIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student-verification': {
      id: '/api/student-verification'
      path: '/api/student-verification'
      fullPath: '/api/student-verification'
      preLoaderRoute: typeof ApiStudentVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/applications/$clientId': {
      id: '/applications/$clientId'
      path: '/$clientId'
      fullPath: '/applications/$clientId'
      preLoaderRoute: typeof ApplicationsClientIdRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/applications/service-new': {
      id: '/applications/service-new'
      path: '/service-new'
      fullPath: '/applications/service-new'
      preLoaderRoute: typeof ApplicationsServiceNewRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/access/permissions/': {
      id: '/access/permissions/'
      path: '/permissions'
      fullPath: '/access/permissions/'
      preLoaderRoute: typeof AccessPermissionsIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/permissions/$permissionId': {
      id: '/access/permissions/$permissionId'
      path: '/permissions/$permissionId'
      fullPath: '/access/permissions/$permissionId'
      preLoaderRoute: typeof AccessPermissionsPermissionIdRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/permissions/new': {
      id: '/access/permissions/new'
      path: '/permissions/new'
      fullPath: '/access/permissions/new'
      preLoaderRoute: typeof AccessPermissionsNewRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/': {
      id: '/access/roles/'
      path: '/roles'
      fullPath: '/access/roles/'
      preLoaderRoute: typeof AccessRolesIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/$roleId': {
      id: '/access/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/access/roles/$roleId'
      preLoaderRoute: typeof AccessRolesRoleIdRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/new': {
      id: '/access/roles/new'
      path: '/roles/new'
      fullPath: '/access/roles/new'
      preLoaderRoute: typeof AccessRolesNewRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/api/accounts/unlink': {
      id: '/api/accounts/unlink'
      path: '/api/accounts/unlink'
      fullPath: '/api/accounts/unlink'
      preLoaderRoute: typeof ApiAccountsUnlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/login': {
      id: '/api/dev/login'
      path: '/api/dev/login'
      fullPath: '/api/dev/login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/idp/access': {
      id: '/api/idp/access'
      path: '/api/idp/access'
      fullPath: '/api/idp/access'
      preLoaderRoute: typeof ApiIdpAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/access-snapshot': {
      id: '/api/internal/access-snapshot'
      path: '/api/internal/access-snapshot'
      fullPath: '/api/internal/access-snapshot'
      preLoaderRoute: typeof ApiInternalAccessSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/client-update': {
      id: '/api/oidc/client-update'
      path: '/api/oidc/client-update'
      fullPath: '/api/oidc/client-update'
      preLoaderRoute: typeof ApiOidcClientUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/clients': {
      id: '/api/oidc/clients'
      path: '/api/oidc/clients'
      fullPath: '/api/oidc/clients'
      preLoaderRoute: typeof ApiOidcClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/resource-link': {
      id: '/api/oidc/resource-link'
      path: '/api/oidc/resource-link'
      fullPath: '/api/oidc/resource-link'
      preLoaderRoute: typeof ApiOidcResourceLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/service-client': {
      id: '/api/oidc/service-client'
      path: '/api/oidc/service-client'
      fullPath: '/api/oidc/service-client'
      preLoaderRoute: typeof ApiOidcServiceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/catalog': {
      id: '/api/rbac/catalog'
      path: '/api/rbac/catalog'
      fullPath: '/api/rbac/catalog'
      preLoaderRoute: typeof ApiRbacCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/permission-save': {
      id: '/api/rbac/permission-save'
      path: '/api/rbac/permission-save'
      fullPath: '/api/rbac/permission-save'
      preLoaderRoute: typeof ApiRbacPermissionSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/role-members': {
      id: '/api/rbac/role-members'
      path: '/api/rbac/role-members'
      fullPath: '/api/rbac/role-members'
      preLoaderRoute: typeof ApiRbacRoleMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/role-save': {
      id: '/api/rbac/role-save'
      path: '/api/rbac/role-save'
      fullPath: '/api/rbac/role-save'
      preLoaderRoute: typeof ApiRbacRoleSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/users': {
      id: '/api/rbac/users'
      path: '/api/rbac/users'
      fullPath: '/api/rbac/users'
      preLoaderRoute: typeof ApiRbacUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/api/users/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccessRouteRouteChildren {
  AccessIndexRoute: typeof AccessIndexRoute
  AccessPermissionsPermissionIdRoute: typeof AccessPermissionsPermissionIdRoute
  AccessPermissionsNewRoute: typeof AccessPermissionsNewRoute
  AccessRolesRoleIdRoute: typeof AccessRolesRoleIdRoute
  AccessRolesNewRoute: typeof AccessRolesNewRoute
  AccessPermissionsIndexRoute: typeof AccessPermissionsIndexRoute
  AccessRolesIndexRoute: typeof AccessRolesIndexRoute
}

const AccessRouteRouteChildren: AccessRouteRouteChildren = {
  AccessIndexRoute: AccessIndexRoute,
  AccessPermissionsPermissionIdRoute: AccessPermissionsPermissionIdRoute,
  AccessPermissionsNewRoute: AccessPermissionsNewRoute,
  AccessRolesRoleIdRoute: AccessRolesRoleIdRoute,
  AccessRolesNewRoute: AccessRolesNewRoute,
  AccessPermissionsIndexRoute: AccessPermissionsIndexRoute,
  AccessRolesIndexRoute: AccessRolesIndexRoute,
}

const AccessRouteRouteWithChildren = AccessRouteRoute._addFileChildren(
  AccessRouteRouteChildren,
)

interface ApplicationsRouteRouteChildren {
  ApplicationsClientIdRoute: typeof ApplicationsClientIdRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  ApplicationsServiceNewRoute: typeof ApplicationsServiceNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteRouteChildren: ApplicationsRouteRouteChildren = {
  ApplicationsClientIdRoute: ApplicationsClientIdRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  ApplicationsServiceNewRoute: ApplicationsServiceNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteRouteWithChildren =
  ApplicationsRouteRoute._addFileChildren(ApplicationsRouteRouteChildren)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRouteRoute: AccessRouteRouteWithChildren,
  ApplicationsRouteRoute: ApplicationsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  ApiIdentityRoute: ApiIdentityRoute,
  ApiProvidersRoute: ApiProvidersRoute,
  ApiStudentVerificationRoute: ApiStudentVerificationRoute,
  ApiAccountsUnlinkRoute: ApiAccountsUnlinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiIdpAccessRoute: ApiIdpAccessRoute,
  ApiInternalAccessSnapshotRoute: ApiInternalAccessSnapshotRoute,
  ApiOidcClientUpdateRoute: ApiOidcClientUpdateRoute,
  ApiOidcClientsRoute: ApiOidcClientsRoute,
  ApiOidcResourceLinkRoute: ApiOidcResourceLinkRoute,
  ApiOidcServiceClientRoute: ApiOidcServiceClientRoute,
  ApiRbacCatalogRoute: ApiRbacCatalogRoute,
  ApiRbacPermissionSaveRoute: ApiRbacPermissionSaveRoute,
  ApiRbacRoleMembersRoute: ApiRbacRoleMembersRoute,
  ApiRbacRoleSaveRoute: ApiRbacRoleSaveRoute,
  ApiRbacUsersRoute: ApiRbacUsersRoute,
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
