/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteRouteImport } from './routes/access/route'
import { Route as ApplicationsRouteRouteImport } from './routes/applications/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AccessIndexRouteImport } from './routes/access/index'
import { Route as ApiIdentityRouteImport } from './routes/api/identity'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiStudentVerificationRouteImport } from './routes/api/student-verification'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsClientIdRouteImport } from './routes/applications/$clientId'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as AccessPermissionsIndexRouteImport } from './routes/access/permissions/index'
import { Route as AccessPermissionsPermissionIdRouteImport } from './routes/access/permissions/$permissionId'
import { Route as AccessPermissionsNewRouteImport } from './routes/access/permissions/new'
import { Route as AccessRolesIndexRouteImport } from './routes/access/roles/index'
import { Route as AccessRolesRoleIdRouteImport } from './routes/access/roles/$roleId'
import { Route as AccessRolesNewRouteImport } from './routes/access/roles/new'
import { Route as ApiAccountsUnlinkRouteImport } from './routes/api/accounts/unlink'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIdpAccessRouteImport } from './routes/api/idp/access'
import { Route as ApiOidcClientUpdateRouteImport } from './routes/api/oidc/client-update'
import { Route as ApiOidcClientsRouteImport } from './routes/api/oidc/clients'
import { Route as ApiRbacCatalogRouteImport } from './routes/api/rbac/catalog'
import { Route as ApiRbacPermissionSaveRouteImport } from './routes/api/rbac/permission-save'
import { Route as ApiRbacRoleMembersRouteImport } from './routes/api/rbac/role-members'
import { Route as ApiRbacRoleSaveRouteImport } from './routes/api/rbac/role-save'
import { Route as ApiRbacUsersRouteImport } from './routes/api/rbac/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRouteRoute = AccessRouteRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRouteRoute = ApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessIndexRoute = AccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const ApiIdentityRoute = ApiIdentityRouteImport.update({
  id: '/api/identity',
  path: '/api/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentVerificationRoute = ApiStudentVerificationRouteImport.update({
  id: '/api/student-verification',
  path: '/api/student-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const ApplicationsClientIdRoute = ApplicationsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const AccessPermissionsIndexRoute = AccessPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessPermissionsPermissionIdRoute =
  AccessPermissionsPermissionIdRouteImport.update({
    id: '/permissions/$permissionId',
    path: '/permissions/$permissionId',
    getParentRoute: () => AccessRouteRoute,
  } as any)
const AccessPermissionsNewRoute = AccessPermissionsNewRouteImport.update({
  id: '/permissions/new',
  path: '/permissions/new',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesIndexRoute = AccessRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesRoleIdRoute = AccessRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AccessRouteRoute,
} as any)
const AccessRolesNewRoute = AccessRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AccessRouteRoute,
} as any)
const ApiAccountsUnlinkRoute = ApiAccountsUnlinkRouteImport.update({
  id: '/api/accounts/unlink',
  path: '/api/accounts/unlink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdpAccessRoute = ApiIdpAccessRouteImport.update({
  id: '/api/idp/access',
  path: '/api/idp/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcClientUpdateRoute = ApiOidcClientUpdateRouteImport.update({
  id: '/api/oidc/client-update',
  path: '/api/oidc/client-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOidcClientsRoute = ApiOidcClientsRouteImport.update({
  id: '/api/oidc/clients',
  path: '/api/oidc/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacCatalogRoute = ApiRbacCatalogRouteImport.update({
  id: '/api/rbac/catalog',
  path: '/api/rbac/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacPermissionSaveRoute = ApiRbacPermissionSaveRouteImport.update({
  id: '/api/rbac/permission-save',
  path: '/api/rbac/permission-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacRoleMembersRoute = ApiRbacRoleMembersRouteImport.update({
  id: '/api/rbac/role-members',
  path: '/api/rbac/role-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacRoleSaveRoute = ApiRbacRoleSaveRouteImport.update({
  id: '/api/rbac/role-save',
  path: '/api/rbac/role-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRbacUsersRoute = ApiRbacUsersRouteImport.update({
  id: '/api/rbac/users',
  path: '/api/rbac/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRouteRouteWithChildren
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/access/': typeof AccessIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/access/permissions/': typeof AccessPermissionsIndexRoute
  '/access/roles/': typeof AccessRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/access': typeof AccessIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/access/permissions': typeof AccessPermissionsIndexRoute
  '/access/roles': typeof AccessRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRouteRouteWithChildren
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/api/identity': typeof ApiIdentityRoute
  '/api/providers': typeof ApiProvidersRoute
  '/api/student-verification': typeof ApiStudentVerificationRoute
  '/applications/$clientId': typeof ApplicationsClientIdRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/access/': typeof AccessIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/access/permissions/$permissionId': typeof AccessPermissionsPermissionIdRoute
  '/access/permissions/new': typeof AccessPermissionsNewRoute
  '/access/roles/$roleId': typeof AccessRolesRoleIdRoute
  '/access/roles/new': typeof AccessRolesNewRoute
  '/api/accounts/unlink': typeof ApiAccountsUnlinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/idp/access': typeof ApiIdpAccessRoute
  '/api/oidc/client-update': typeof ApiOidcClientUpdateRoute
  '/api/oidc/clients': typeof ApiOidcClientsRoute
  '/api/rbac/catalog': typeof ApiRbacCatalogRoute
  '/api/rbac/permission-save': typeof ApiRbacPermissionSaveRoute
  '/api/rbac/role-members': typeof ApiRbacRoleMembersRoute
  '/api/rbac/role-save': typeof ApiRbacRoleSaveRoute
  '/api/rbac/users': typeof ApiRbacUsersRoute
  '/access/permissions/': typeof AccessPermissionsIndexRoute
  '/access/roles/': typeof AccessRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/applications'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/access/'
    | '/applications/'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/idp/access'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/access/permissions/'
    | '/access/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/access'
    | '/applications'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/idp/access'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/access/permissions'
    | '/access/roles'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/applications'
    | '/consent'
    | '/api/identity'
    | '/api/providers'
    | '/api/student-verification'
    | '/applications/$clientId'
    | '/applications/new'
    | '/access/'
    | '/applications/'
    | '/access/permissions/$permissionId'
    | '/access/permissions/new'
    | '/access/roles/$roleId'
    | '/access/roles/new'
    | '/api/accounts/unlink'
    | '/api/auth/$'
    | '/api/idp/access'
    | '/api/oidc/client-update'
    | '/api/oidc/clients'
    | '/api/rbac/catalog'
    | '/api/rbac/permission-save'
    | '/api/rbac/role-members'
    | '/api/rbac/role-save'
    | '/api/rbac/users'
    | '/access/permissions/'
    | '/access/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRouteRoute: typeof AccessRouteRouteWithChildren
  ApplicationsRouteRoute: typeof ApplicationsRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  ApiIdentityRoute: typeof ApiIdentityRoute
  ApiProvidersRoute: typeof ApiProvidersRoute
  ApiStudentVerificationRoute: typeof ApiStudentVerificationRoute
  ApiAccountsUnlinkRoute: typeof ApiAccountsUnlinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIdpAccessRoute: typeof ApiIdpAccessRoute
  ApiOidcClientUpdateRoute: typeof ApiOidcClientUpdateRoute
  ApiOidcClientsRoute: typeof ApiOidcClientsRoute
  ApiRbacCatalogRoute: typeof ApiRbacCatalogRoute
  ApiRbacPermissionSaveRoute: typeof ApiRbacPermissionSaveRoute
  ApiRbacRoleMembersRoute: typeof ApiRbacRoleMembersRoute
  ApiRbacRoleSaveRoute: typeof ApiRbacRoleSaveRoute
  ApiRbacUsersRoute: typeof ApiRbacUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/': {
      id: '/access/'
      path: '/'
      fullPath: '/access/'
      preLoaderRoute: typeof AccessIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/api/identity': {
      id: '/api/identity'
      path: '/api/identity'
      fullPath: '/api/identity'
      preLoaderRoute: typeof ApiIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student-verification': {
      id: '/api/student-verification'
      path: '/api/student-verification'
      fullPath: '/api/student-verification'
      preLoaderRoute: typeof ApiStudentVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/applications/$clientId': {
      id: '/applications/$clientId'
      path: '/$clientId'
      fullPath: '/applications/$clientId'
      preLoaderRoute: typeof ApplicationsClientIdRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/access/permissions/': {
      id: '/access/permissions/'
      path: '/permissions'
      fullPath: '/access/permissions/'
      preLoaderRoute: typeof AccessPermissionsIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/permissions/$permissionId': {
      id: '/access/permissions/$permissionId'
      path: '/permissions/$permissionId'
      fullPath: '/access/permissions/$permissionId'
      preLoaderRoute: typeof AccessPermissionsPermissionIdRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/permissions/new': {
      id: '/access/permissions/new'
      path: '/permissions/new'
      fullPath: '/access/permissions/new'
      preLoaderRoute: typeof AccessPermissionsNewRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/': {
      id: '/access/roles/'
      path: '/roles'
      fullPath: '/access/roles/'
      preLoaderRoute: typeof AccessRolesIndexRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/$roleId': {
      id: '/access/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/access/roles/$roleId'
      preLoaderRoute: typeof AccessRolesRoleIdRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/access/roles/new': {
      id: '/access/roles/new'
      path: '/roles/new'
      fullPath: '/access/roles/new'
      preLoaderRoute: typeof AccessRolesNewRouteImport
      parentRoute: typeof AccessRouteRoute
    }
    '/api/accounts/unlink': {
      id: '/api/accounts/unlink'
      path: '/api/accounts/unlink'
      fullPath: '/api/accounts/unlink'
      preLoaderRoute: typeof ApiAccountsUnlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/idp/access': {
      id: '/api/idp/access'
      path: '/api/idp/access'
      fullPath: '/api/idp/access'
      preLoaderRoute: typeof ApiIdpAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/client-update': {
      id: '/api/oidc/client-update'
      path: '/api/oidc/client-update'
      fullPath: '/api/oidc/client-update'
      preLoaderRoute: typeof ApiOidcClientUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oidc/clients': {
      id: '/api/oidc/clients'
      path: '/api/oidc/clients'
      fullPath: '/api/oidc/clients'
      preLoaderRoute: typeof ApiOidcClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/catalog': {
      id: '/api/rbac/catalog'
      path: '/api/rbac/catalog'
      fullPath: '/api/rbac/catalog'
      preLoaderRoute: typeof ApiRbacCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/permission-save': {
      id: '/api/rbac/permission-save'
      path: '/api/rbac/permission-save'
      fullPath: '/api/rbac/permission-save'
      preLoaderRoute: typeof ApiRbacPermissionSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/role-members': {
      id: '/api/rbac/role-members'
      path: '/api/rbac/role-members'
      fullPath: '/api/rbac/role-members'
      preLoaderRoute: typeof ApiRbacRoleMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/role-save': {
      id: '/api/rbac/role-save'
      path: '/api/rbac/role-save'
      fullPath: '/api/rbac/role-save'
      preLoaderRoute: typeof ApiRbacRoleSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rbac/users': {
      id: '/api/rbac/users'
      path: '/api/rbac/users'
      fullPath: '/api/rbac/users'
      preLoaderRoute: typeof ApiRbacUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccessRouteRouteChildren {
  AccessIndexRoute: typeof AccessIndexRoute
  AccessPermissionsPermissionIdRoute: typeof AccessPermissionsPermissionIdRoute
  AccessPermissionsNewRoute: typeof AccessPermissionsNewRoute
  AccessRolesRoleIdRoute: typeof AccessRolesRoleIdRoute
  AccessRolesNewRoute: typeof AccessRolesNewRoute
  AccessPermissionsIndexRoute: typeof AccessPermissionsIndexRoute
  AccessRolesIndexRoute: typeof AccessRolesIndexRoute
}

const AccessRouteRouteChildren: AccessRouteRouteChildren = {
  AccessIndexRoute: AccessIndexRoute,
  AccessPermissionsPermissionIdRoute: AccessPermissionsPermissionIdRoute,
  AccessPermissionsNewRoute: AccessPermissionsNewRoute,
  AccessRolesRoleIdRoute: AccessRolesRoleIdRoute,
  AccessRolesNewRoute: AccessRolesNewRoute,
  AccessPermissionsIndexRoute: AccessPermissionsIndexRoute,
  AccessRolesIndexRoute: AccessRolesIndexRoute,
}

const AccessRouteRouteWithChildren = AccessRouteRoute._addFileChildren(
  AccessRouteRouteChildren,
)

interface ApplicationsRouteRouteChildren {
  ApplicationsClientIdRoute: typeof ApplicationsClientIdRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteRouteChildren: ApplicationsRouteRouteChildren = {
  ApplicationsClientIdRoute: ApplicationsClientIdRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteRouteWithChildren =
  ApplicationsRouteRoute._addFileChildren(ApplicationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRouteRoute: AccessRouteRouteWithChildren,
  ApplicationsRouteRoute: ApplicationsRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  ApiIdentityRoute: ApiIdentityRoute,
  ApiProvidersRoute: ApiProvidersRoute,
  ApiStudentVerificationRoute: ApiStudentVerificationRoute,
  ApiAccountsUnlinkRoute: ApiAccountsUnlinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIdpAccessRoute: ApiIdpAccessRoute,
  ApiOidcClientUpdateRoute: ApiOidcClientUpdateRoute,
  ApiOidcClientsRoute: ApiOidcClientsRoute,
  ApiRbacCatalogRoute: ApiRbacCatalogRoute,
  ApiRbacPermissionSaveRoute: ApiRbacPermissionSaveRoute,
  ApiRbacRoleMembersRoute: ApiRbacRoleMembersRoute,
  ApiRbacRoleSaveRoute: ApiRbacRoleSaveRoute,
  ApiRbacUsersRoute: ApiRbacUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
